"""The Analysis aggregate root — the heart of the domain.

It models the lifecycle of a single medical-image analysis, independent of any
database, web framework or AI library. State transitions are expressed as
behavior on the entity so business rules live in one place.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum
from uuid import UUID, uuid4

from app.domain.value_objects.prediction import PredictedClass, Prediction

EDUCATIONAL_WARNING = (
    "This result is generated by an educational AI demo. "
    "It is NOT a medical diagnosis. Always consult a licensed physician."
)


class AnalysisStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


def _utcnow() -> datetime:
    return datetime.now(UTC)


@dataclass
class Analysis:
    original_filename: str
    stored_filename: str
    image_path: str
    id: UUID = field(default_factory=uuid4)
    status: AnalysisStatus = AnalysisStatus.PENDING
    predicted_class: PredictedClass | None = None
    confidence_score: float | None = None
    explanation: str | None = None
    processing_time_ms: int | None = None
    error_message: str | None = None
    findings: dict[str, float] | None = None
    created_at: datetime = field(default_factory=_utcnow)
    updated_at: datetime = field(default_factory=_utcnow)

    # --- behavior / state transitions ---
    def mark_processing(self) -> None:
        self.status = AnalysisStatus.PROCESSING
        self.updated_at = _utcnow()

    def complete(self, prediction: Prediction) -> None:
        self.status = AnalysisStatus.COMPLETED
        self.predicted_class = prediction.predicted_class
        self.confidence_score = prediction.confidence_score
        self.processing_time_ms = prediction.processing_time_ms
        self.explanation = prediction.explanation()
        self.findings = prediction.findings or prediction.class_probabilities
        self.error_message = None
        self.updated_at = _utcnow()

    def fail(self, error_message: str) -> None:
        self.status = AnalysisStatus.FAILED
        self.error_message = error_message
        self.updated_at = _utcnow()

    @property
    def warning(self) -> str:
        return EDUCATIONAL_WARNING
